### ISSUE TITLE
Blank buttons

### ISSUE THREAD

**Issue by danieloprado** [mpicciolli/angular-material-picker#1]
All buttons are now blank, without any text

![image](https://cloud.githubusercontent.com/assets/7683575/23210729/a5a6794e-f8dd-11e6-9eb8-514acb77db6e.png)

![image](https://cloud.githubusercontent.com/assets/7683575/23210791/e1ce0d60-f8dd-11e6-9450-2c8743e63849.png)

My directive:
```js
(function(angular) {
  'use strict';

  angular.module('app').directive('datepicker', DatePicker);

  function DatePicker($compile, $mdpDatePicker) {

    return {
      restric: 'A',
      scope: {
        ngModel: '='
      },
      priority: 1,
      replace: false,
      terminal: true,
      compile: (tElement, tAttrs) => {
        tElement.removeAttr('datepicker');
        tElement.before('<md-icon md-svg-icon="calendar" ng-click="showPicker($event)"></md-icon>');
        tElement.parent('md-input-container').addClass('md-icon-float md-icon-left');
        tAttrs.$set('ui-date-mask', '');

        return {
          pre: ($scope, iElement) => {
            $scope.showPicker = (targetEvent) => {
              if (iElement.attr('disabled')) return;

              $mdpDatePicker($scope.ngModel, { targetEvent })
                .then(selectedDate => $scope.ngModel = selectedDate);
            };

            $compile(iElement)($scope);
          }
        };
      }
    };

  }
  DatePicker.$inject = ['$compile', '$mdpDatePicker'];


})(angular);
```

**Comment by mpicciolli** [comment]
Hi,

In your html use mdp-confirm-text & mdp-cancel-text attributes like this : 

`<mdp-time-picker ng-model="timer.value" mdp-format="HH:mm" mdp-confirm-text="{{'ok' | translate}}" mdp-cancel-text="{{'cancel' | translate}}"></mdp-time-picker>`

**Comment by mpicciolli** [comment]
Hi,

Use confirmText & cancelText attributes.

For example in html : 
`<mdp-time-picker ng-model="timer.value" mdp-format="HH:mm" mdp-confirm-text="{{'ok' | translate}}" mdp-cancel-text="{{'cancel' | translate}}"></mdp-time-picker>`
